### ISSUE TITLE
update of statistic

### ISSUE THREAD

**Issue by LeoBolien** [tgoetten/mailarchiva-dockerized#3] opened 2024-01-10 15:26 UTC
Hello,
thanks for your docker project to run mailarchiva in docker container. Overall mailarchiva runs as expected inside docker
container based on your description here.
One thing i have :-( If i try to update statistic this will not work. I get the following error messgae back (from log):

`2024-01-10 16:09:58,023 starting Analytics erstellen /var/opt/vol/index/vol202401...
2024-01-10 16:09:58,028 Process exception, got java.lang.Exception: failed to allocate Memory, increase it.
java.util.concurrent.ExecutionException: java.lang.Exception: failed to allocate Memory, increase it. ...`

I tried different things to increase the memory (e.g. CATALINA__OPS) but nothing helped. My Docker environment have 
enough memory (around 8GB)

To you have an idea here ?

Thanks Leo

**Comment by tgoetten** [comment] 2024-01-22 20:01
Hello @LeoBolien ,

First off, thank you for bringing this to my attention. I must admit, this specific issue was not previously known to me, and I appreciate you detailing your experience and the troubles you've encountered.

Upon receiving your message, I took the time to replicate the setup on my end, and indeed, I was able to reproduce the issue you described. It's clear now that despite attempts to increase memory allocation through various means like CATALINA__OPS, the problem persists, which is quite perplexing considering the ample memory (around 8GB) available in your Docker environment.

I want to assure you that I take this issue seriously and am currently investigating the underlying cause. Unfortunately, I haven't been able to devise a quick fix that resolves the memory allocation error. It seems to be a more complex problem than initially anticipated.

Given the situation, I kindly ask for a bit more time to thoroughly explore potential solutions and workarounds. 

Please rest assured, I am on it and will update the repository with any findings, solutions, or workarounds as soon as possible.

Best,
Thomas

**Comment by tgoetten** [comment] 2024-12-17 10:20
> Hello, thanks for your docker project to run mailarchiva in docker container. Overall mailarchiva runs as expected inside docker container based on your description here. One thing i have :-( If i try to update statistic this will not work. I get the following error messgae back (from log):
> 
> `2024-01-10 16:09:58,023 starting Analytics erstellen /var/opt/vol/index/vol202401... 2024-01-10 16:09:58,028 Process exception, got java.lang.Exception: failed to allocate Memory, increase it. java.util.concurrent.ExecutionException: java.lang.Exception: failed to allocate Memory, increase it. ...`
> 
> I tried different things to increase the memory (e.g. CATALINA__OPS) but nothing helped. My Docker environment have enough memory (around 8GB)
> 
> To you have an idea here ?
> 
> Thanks Leo

Hi Leo,

I've updated the Docker container to use Mailarchiva v9, which resolves the statistic generation issue you reported (at least on my end). The new version uses the official Tomcat image and works smoothly.

I'll be closing this issue as v8 is no longer supported. Please try the latest version and let me know if you have any questions.
Best regards,
Thomas

**Closed as completed by tgoetten** 2024-12-17 10:20 UTC
